<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class LinkHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['href'])) {
            $value = $data['href'];
            $return = (string) $value;
            $this->class->reflFields['href']->setValue($document, $return);
            $hydratedData['href'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['text'])) {
            $value = $data['text'];
            $return = (string) $value;
            $this->class->reflFields['text']->setValue($document, $return);
            $hydratedData['text'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['level'])) {
            $value = $data['level'];
            $return = (int) $value;
            $this->class->reflFields['level']->setValue($document, $return);
            $hydratedData['level'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['status'])) {
            $value = $data['status'];
            $return = (int) $value;
            $this->class->reflFields['status']->setValue($document, $return);
            $hydratedData['status'] = $return;
        }
        return $hydratedData;
    }
}